### ISSUE TITLE
failing for login.yml

### ISSUE THREAD

**Issue by A1ve5** [CSCfi/ansible-role-yum#1]
TASK: [ansible-role-yum | disable and stop services] *************************\* 
failed: [io.fgci.csc.fi] => {"failed": true, "item": ""}
msg: No ActiveState value in systemctl show output for ''

FATAL: all hosts have already failed -- aborting

**Comment by martbhell** [comment]
Moved to group_vars/all/all in fgci-ansible repository https://github.com/CSC-IT-Center-for-Science/fgci-ansible/commit/ddce8f99401c226ee71f2ed65df13f4922ac4d1f

Also https://github.com/CSC-IT-Center-for-Science/ansible-role-yum/commit/036a860602c0dfcb7141766b5c5adfc40968e139 which should this error.
Not confirmed yet.

**Comment by martbhell** [comment]
No problems with this during a reinstall. marking as solved.
