### ISSUE TITLE
limit number of installed kernel versions to 3

### ISSUE THREAD

**Issue by A1ve5** [CSCfi/ansible-role-yum#5]
in yum.conf https://github.com/CSC-IT-Center-for-Science/ansible-role-yum/blob/master/templates/yum.conf.j2 we have "installonly_limit=5" - should we lower this to say 3?

**Comment by martbhell** [comment]
https://github.com/CSC-IT-Center-for-Science/ansible-role-yum/commit/e460db98acb7a724eedba89816ad13086edb0549
